# frozen_string_literal: true

require 'spec_helper'
require 'tempfile'

RSpec.describe DbBeforeAfter::HtmlOutputAdapter do
  let(:tempfile) { Tempfile.new('test_output.html') }
  let(:adapter) { described_class.new(tempfile) }

  after { tempfile.close }

  describe '#initialize' do
    it 'sets file correctly' do
      expect(adapter.send(:file)).to eq(tempfile)
    end
  end

  describe '#start_output' do
    it 'writes modern HTML document start with CSS' do
      adapter.start_output
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('<!DOCTYPE html>')
      expect(content).to include('<html lang="en">')
      expect(content).to include('<head>')
      expect(content).to include('<meta charset="UTF-8">')
      expect(content).to include('<meta name="viewport"')
      expect(content).to include('<title>Database Diff Report</title>')
      expect(content).to include('<style>')
      expect(content).to include('font-family: -apple-system')
      expect(content).to include('</style>')
      expect(content).to include('</head>')
      expect(content).to include('<body>')
      expect(content).to include('<div class="container">')
      expect(content).to include('<header class="header">')
      expect(content).to include('<h1>Database Diff Report</h1>')
      expect(content).to include('<main class="main-content">')
    end
  end

  describe '#end_output' do
    it 'writes modern HTML document end' do
      adapter.end_output
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('</main>')
      expect(content).to include('<footer class="footer">')
      expect(content).to include('Generated by')
      expect(content).to include('db_before_after')
      expect(content).to include('</footer>')
      expect(content).to include('</div>')
      expect(content).to include('</body>')
      expect(content).to include('</html>')
    end
  end

  describe '#write_title' do
    it 'writes modern HTML section with title' do
      adapter.write_title('Test Title')
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('<section class="table-section">')
      expect(content).to include('<h2 class="table-title">Test Title</h2>')
      expect(content).to include('<div class="diff-container">')
    end
  end

  describe '#write_diff_section' do
    it 'writes modern diff section with headers' do
      adapter.write_diff_section('left content', 'right content')
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('<div class="diff-part">')
      expect(content).to include('<div class="diff-side diff-left">')
      expect(content).to include('<h3 class="diff-header">Before</h3>')
      expect(content).to include('<div class="diff-content">left content</div>')
      expect(content).to include('<div class="diff-side diff-right">')
      expect(content).to include('<h3 class="diff-header">After</h3>')
      expect(content).to include('<div class="diff-content">right content</div>')
    end
  end

  describe '#write_no_diff_message' do
    it 'writes modern no diff message' do
      adapter.write_no_diff_message
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('<div class="no-diff-message">')
      expect(content).to include('<div class="no-diff-icon">✅</div>')
      expect(content).to include('<h2>No Changes Detected</h2>')
      expect(content).to include('<p>The database state remained unchanged')
    end
  end

  describe '#generate_diff' do
    it 'returns Diffy::SplitDiff object' do
      result = adapter.generate_diff('left content', 'right content')
      
      expect(result).to be_a(Diffy::SplitDiff)
    end

    it 'generates HTML format diff' do
      result = adapter.generate_diff('old text', 'new text')
      
      expect(result.left).to include('<div class="diff">')
      expect(result.right).to include('<div class="diff">')
    end
  end

  describe '#format_content' do
    it 'replaces spaces with &nbsp; and newlines with <br/>' do
      input = "Hello World\nSecond Line"
      expected = "Hello&nbsp;World<br/>Second&nbsp;Line"
      
      result = adapter.format_content(input)
      expect(result).to eq(expected)
    end

    it 'returns nil when input is nil' do
      result = adapter.format_content(nil)
      expect(result).to be_nil
    end
  end

  describe '#close_section' do
    it 'closes the section properly' do
      adapter.close_section
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('</div>')
      expect(content).to include('</section>')
    end
  end

  describe 'full HTML generation' do
    it 'generates complete modern HTML document' do
      adapter.start_output
      adapter.write_title('Test Table')
      adapter.write_diff_section('left diff', 'right diff')
      adapter.close_section
      adapter.write_no_diff_message
      adapter.end_output
      
      tempfile.rewind
      content = tempfile.read
      
      expect(content).to include('<!DOCTYPE html>')
      expect(content).to include('<html lang="en">')
      expect(content).to include('<div class="container">')
      expect(content).to include('<header class="header">')
      expect(content).to include('<h1>Database Diff Report</h1>')
      expect(content).to include('<section class="table-section">')
      expect(content).to include('<h2 class="table-title">Test Table</h2>')
      expect(content).to include('<div class="diff-part">')
      expect(content).to include('left diff')
      expect(content).to include('right diff')
      expect(content).to include('<div class="no-diff-message">')
      expect(content).to include('<footer class="footer">')
      expect(content).to include('</html>')
    end
  end
end